create schema if not exists vlr_private;
revoke all on schema vlr_private from public, anon, authenticated;

create table public.vlr_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  avatar_url text,
  date_of_birth date,
  phone text,
  gender text check (gender in ('female', 'male', 'non_binary', 'prefer_not_to_say')),
  role text not null default 'customer' check (role in ('customer', 'admin')),
  loyalty_points integer not null default 0 check (loyalty_points >= 0),
  saved_sizes jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.vlr_departments (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.vlr_categories (
  id bigint generated by default as identity primary key,
  department_id bigint not null references public.vlr_departments(id) on delete cascade,
  slug text not null,
  name text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (department_id, slug)
);

create table public.vlr_collections (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  description text,
  cover_image_url text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.vlr_products (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  description text not null,
  department_id bigint not null references public.vlr_departments(id),
  category_id bigint not null references public.vlr_categories(id),
  product_type text not null,
  base_price numeric(14,2) not null check (base_price >= 0),
  material text,
  care text,
  shipping_note text,
  return_policy text,
  primary_image_url text not null,
  hover_image_url text,
  video_url text,
  is_available boolean not null default true,
  is_featured boolean not null default false,
  is_new_arrival boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.vlr_product_media (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.vlr_products(id) on delete cascade,
  media_type text not null check (media_type in ('product', 'model', 'detail', 'video')),
  url text not null,
  alt_text text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.vlr_product_variants (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.vlr_products(id) on delete cascade,
  sku text not null unique,
  option_values jsonb not null default '{}'::jsonb,
  price_adjustment numeric(14,2) not null default 0,
  stock integer not null default 0 check (stock >= 0),
  low_stock_threshold integer not null default 3 check (low_stock_threshold >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.vlr_product_collections (
  product_id uuid not null references public.vlr_products(id) on delete cascade,
  collection_id uuid not null references public.vlr_collections(id) on delete cascade,
  sort_order integer not null default 0,
  primary key (product_id, collection_id)
);

create table public.vlr_wishlist_items (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id uuid not null references public.vlr_products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table public.vlr_bag_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  variant_id uuid not null references public.vlr_product_variants(id) on delete cascade,
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, variant_id)
);

create table public.vlr_recently_viewed (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id uuid not null references public.vlr_products(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table public.vlr_addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null default 'Home',
  recipient_name text not null,
  phone text not null,
  address_line_1 text not null,
  address_line_2 text,
  city text not null,
  state_region text,
  postal_code text,
  country text not null default 'Myanmar',
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.vlr_orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique default ('VL-' || to_char(now(), 'YYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6))),
  user_id uuid not null references auth.users(id),
  status text not null default 'pending_payment' check (status in ('pending_payment','confirmed','preparing','quality_inspection','luxury_packaging','shipped','delivered','cancelled','return_in_progress','refunded')),
  payment_status text not null default 'awaiting_payment' check (payment_status in ('awaiting_payment','payment_submitted','verified','rejected','refunded')),
  contact_email text not null,
  contact_phone text not null,
  delivery_address jsonb not null,
  delivery_method text not null default 'standard',
  subtotal numeric(14,2) not null check (subtotal >= 0),
  discount numeric(14,2) not null default 0 check (discount >= 0),
  loyalty_discount numeric(14,2) not null default 0 check (loyalty_discount >= 0),
  delivery_fee numeric(14,2) not null default 0 check (delivery_fee >= 0),
  grand_total numeric(14,2) not null check (grand_total >= 0),
  loyalty_points_earned integer not null default 0,
  loyalty_points_redeemed integer not null default 0,
  delivered_at timestamptz,
  cancellation_requested_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.vlr_order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.vlr_orders(id) on delete cascade,
  product_id uuid references public.vlr_products(id) on delete set null,
  variant_id uuid references public.vlr_product_variants(id) on delete set null,
  product_name text not null,
  variant_snapshot jsonb not null,
  sku text not null,
  unit_price numeric(14,2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  line_total numeric(14,2) not null check (line_total >= 0),
  primary_image_url text,
  created_at timestamptz not null default now()
);

create table public.vlr_payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.vlr_orders(id) on delete cascade,
  user_id uuid not null references auth.users(id),
  provider text not null default 'kpay',
  proof_path text,
  amount numeric(14,2) not null check (amount >= 0),
  status text not null default 'awaiting_payment' check (status in ('awaiting_payment','payment_submitted','verified','rejected','refunded')),
  submitted_at timestamptz,
  verified_at timestamptz,
  verified_by uuid references auth.users(id),
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.vlr_returns (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.vlr_orders(id),
  user_id uuid not null references auth.users(id),
  status text not null default 'requested' check (status in ('requested','under_review','approved','rejected','item_received','inspection','refund_approved','refunded')),
  reason text not null,
  photo_paths text[] not null default '{}',
  admin_note text,
  requested_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.vlr_return_items (
  id uuid primary key default gen_random_uuid(),
  return_id uuid not null references public.vlr_returns(id) on delete cascade,
  order_item_id uuid not null references public.vlr_order_items(id),
  quantity integer not null check (quantity > 0),
  unique (return_id, order_item_id)
);

create table public.vlr_loyalty_transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id),
  order_id uuid references public.vlr_orders(id),
  transaction_type text not null check (transaction_type in ('earned','redeemed','refund_adjustment','admin_adjustment')),
  points integer not null,
  description text not null,
  created_at timestamptz not null default now()
);

create unique index vlr_loyalty_one_earned_per_order on public.vlr_loyalty_transactions(order_id, transaction_type) where transaction_type = 'earned';
create index vlr_products_department_idx on public.vlr_products(department_id, category_id) where is_available;
create index vlr_variants_product_idx on public.vlr_product_variants(product_id) where is_active;
create index vlr_orders_user_idx on public.vlr_orders(user_id, created_at desc);

create table public.vlr_notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  audience text not null default 'customer' check (audience in ('customer','admin')),
  type text not null,
  title text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.vlr_ai_settings (
  id boolean primary key default true check (id),
  enabled boolean not null default true,
  system_note text,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table public.vlr_store_settings (
  id boolean primary key default true check (id),
  kpay_account_name text not null default 'VÉLOIRE Maison',
  kpay_phone text not null default '09 000 000 000',
  kpay_qr_url text,
  delivery_fee numeric(14,2) not null default 5000,
  loyalty_step_amount numeric(14,2) not null default 200000,
  loyalty_step_points integer not null default 10,
  loyalty_redemption_mmk_per_10_points numeric(14,2) not null default 100,
  max_redemption_percent numeric(5,2) not null default 20,
  updated_at timestamptz not null default now()
);

create table public.vlr_admin_audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references auth.users(id),
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function vlr_private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.vlr_profiles
    where id = (select auth.uid()) and role = 'admin'
  );
$$;
revoke all on function vlr_private.is_admin() from public;
grant usage on schema vlr_private to authenticated;
grant execute on function vlr_private.is_admin() to authenticated;

create or replace function vlr_private.touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function vlr_private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.vlr_profiles (id, email, full_name, avatar_url, role)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.raw_user_meta_data ->> 'avatar_url',
    case when lower(coalesce(new.email, '')) = 'lia.thedev@gmail.com' then 'admin' else 'customer' end
  )
  on conflict (id) do update set
    email = excluded.email,
    full_name = coalesce(public.vlr_profiles.full_name, excluded.full_name),
    avatar_url = coalesce(public.vlr_profiles.avatar_url, excluded.avatar_url),
    role = case when lower(excluded.email) = 'lia.thedev@gmail.com' then 'admin' else public.vlr_profiles.role end;
  return new;
end;
$$;
revoke all on function vlr_private.handle_new_user() from public, anon, authenticated;

drop trigger if exists vlr_on_auth_user_created on auth.users;
create trigger vlr_on_auth_user_created
after insert or update of email, raw_user_meta_data on auth.users
for each row execute function vlr_private.handle_new_user();

create or replace function vlr_private.sync_verified_payment()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  earned_points integer;
  order_user uuid;
  eligible numeric(14,2);
begin
  if new.status = 'verified' and old.status is distinct from 'verified' then
    select user_id, greatest(subtotal - discount - loyalty_discount, 0)
      into order_user, eligible
      from public.vlr_orders where id = new.order_id for update;
    earned_points := floor(eligible / 200000)::integer * 10;

    update public.vlr_orders
      set payment_status = 'verified', status = 'confirmed', loyalty_points_earned = earned_points, updated_at = now()
      where id = new.order_id and payment_status <> 'verified';

    if earned_points > 0 then
      insert into public.vlr_loyalty_transactions (user_id, order_id, transaction_type, points, description)
      values (order_user, new.order_id, 'earned', earned_points, 'Points earned from verified order')
      on conflict do nothing;
      if found then
        update public.vlr_profiles set loyalty_points = loyalty_points + earned_points, updated_at = now() where id = order_user;
      end if;
    end if;

    insert into public.vlr_notifications (user_id, audience, type, title, message)
    values (order_user, 'customer', 'payment_verified', 'Payment verified', 'Your order has been confirmed and is entering our care.');
  elsif new.status = 'rejected' and old.status is distinct from 'rejected' then
    update public.vlr_orders set payment_status = 'rejected', updated_at = now() where id = new.order_id;
  end if;
  return new;
end;
$$;
revoke all on function vlr_private.sync_verified_payment() from public, anon, authenticated;

drop trigger if exists vlr_payment_status_sync on public.vlr_payments;
create trigger vlr_payment_status_sync
after update of status on public.vlr_payments
for each row execute function vlr_private.sync_verified_payment();

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'vlr_profiles','vlr_departments','vlr_categories','vlr_collections','vlr_products','vlr_product_media',
    'vlr_product_variants','vlr_product_collections','vlr_wishlist_items','vlr_bag_items','vlr_recently_viewed',
    'vlr_addresses','vlr_orders','vlr_order_items','vlr_payments','vlr_returns','vlr_return_items',
    'vlr_loyalty_transactions','vlr_notifications','vlr_ai_settings','vlr_store_settings','vlr_admin_audit_logs'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
  end loop;
end $$;

create policy "vlr public reads active departments" on public.vlr_departments for select to anon, authenticated using (is_active);
create policy "vlr public reads active categories" on public.vlr_categories for select to anon, authenticated using (is_active);
create policy "vlr public reads active collections" on public.vlr_collections for select to anon, authenticated using (is_active);
create policy "vlr public reads available products" on public.vlr_products for select to anon, authenticated using (is_available);
create policy "vlr public reads product media" on public.vlr_product_media for select to anon, authenticated using (exists (select 1 from public.vlr_products p where p.id = product_id and p.is_available));
create policy "vlr public reads active variants" on public.vlr_product_variants for select to anon, authenticated using (is_active and exists (select 1 from public.vlr_products p where p.id = product_id and p.is_available));
create policy "vlr public reads product collections" on public.vlr_product_collections for select to anon, authenticated using (true);
create policy "vlr public reads store settings" on public.vlr_store_settings for select to anon, authenticated using (true);

create policy "vlr users read own profile" on public.vlr_profiles for select to authenticated using ((select auth.uid()) = id or (select vlr_private.is_admin()));
create policy "vlr users update own profile" on public.vlr_profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

create policy "vlr users own wishlist" on public.vlr_wishlist_items for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "vlr users own bag" on public.vlr_bag_items for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "vlr users own recent views" on public.vlr_recently_viewed for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "vlr users own addresses" on public.vlr_addresses for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "vlr users read own orders" on public.vlr_orders for select to authenticated using ((select auth.uid()) = user_id or (select vlr_private.is_admin()));
create policy "vlr users read own order items" on public.vlr_order_items for select to authenticated using (exists (select 1 from public.vlr_orders o where o.id = order_id and (o.user_id = (select auth.uid()) or (select vlr_private.is_admin()))));
create policy "vlr users read own payments" on public.vlr_payments for select to authenticated using ((select auth.uid()) = user_id or (select vlr_private.is_admin()));
create policy "vlr users read own returns" on public.vlr_returns for select to authenticated using ((select auth.uid()) = user_id or (select vlr_private.is_admin()));
create policy "vlr users create own returns" on public.vlr_returns for insert to authenticated with check ((select auth.uid()) = user_id and exists (select 1 from public.vlr_orders o where o.id = order_id and o.user_id = (select auth.uid()) and o.delivered_at >= now() - interval '14 days'));
create policy "vlr users read own return items" on public.vlr_return_items for select to authenticated using (exists (select 1 from public.vlr_returns r where r.id = return_id and (r.user_id = (select auth.uid()) or (select vlr_private.is_admin()))));
create policy "vlr users read own loyalty" on public.vlr_loyalty_transactions for select to authenticated using ((select auth.uid()) = user_id or (select vlr_private.is_admin()));
create policy "vlr users read own notifications" on public.vlr_notifications for select to authenticated using (user_id = (select auth.uid()) or (audience = 'admin' and (select vlr_private.is_admin())));
create policy "vlr users mark own notifications read" on public.vlr_notifications for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "vlr admins read ai settings" on public.vlr_ai_settings for select to authenticated using ((select vlr_private.is_admin()));
create policy "vlr admins read audit log" on public.vlr_admin_audit_logs for select to authenticated using ((select vlr_private.is_admin()));

revoke all on all tables in schema public from anon, authenticated;
grant select on public.vlr_departments, public.vlr_categories, public.vlr_collections, public.vlr_products, public.vlr_product_media, public.vlr_product_variants, public.vlr_product_collections, public.vlr_store_settings to anon, authenticated;
grant select on public.vlr_profiles, public.vlr_orders, public.vlr_order_items, public.vlr_payments, public.vlr_returns, public.vlr_return_items, public.vlr_loyalty_transactions, public.vlr_notifications, public.vlr_ai_settings, public.vlr_admin_audit_logs to authenticated;
grant select, insert, delete on public.vlr_wishlist_items to authenticated;
grant select, insert, update, delete on public.vlr_bag_items, public.vlr_recently_viewed, public.vlr_addresses to authenticated;
grant update (full_name, avatar_url, date_of_birth, phone, gender, saved_sizes) on public.vlr_profiles to authenticated;
grant insert (order_id, user_id, reason, photo_paths) on public.vlr_returns to authenticated;
grant insert (return_id, order_item_id, quantity) on public.vlr_return_items to authenticated;
grant update (is_read) on public.vlr_notifications to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

create trigger vlr_profiles_touch before update on public.vlr_profiles for each row execute function vlr_private.touch_updated_at();
create trigger vlr_collections_touch before update on public.vlr_collections for each row execute function vlr_private.touch_updated_at();
create trigger vlr_products_touch before update on public.vlr_products for each row execute function vlr_private.touch_updated_at();
create trigger vlr_variants_touch before update on public.vlr_product_variants for each row execute function vlr_private.touch_updated_at();
create trigger vlr_bag_touch before update on public.vlr_bag_items for each row execute function vlr_private.touch_updated_at();
create trigger vlr_addresses_touch before update on public.vlr_addresses for each row execute function vlr_private.touch_updated_at();
create trigger vlr_orders_touch before update on public.vlr_orders for each row execute function vlr_private.touch_updated_at();
create trigger vlr_payments_touch before update on public.vlr_payments for each row execute function vlr_private.touch_updated_at();
create trigger vlr_returns_touch before update on public.vlr_returns for each row execute function vlr_private.touch_updated_at();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('vlr-product-media', 'vlr-product-media', true, 15728640, array['image/jpeg','image/png','image/webp','video/mp4']),
  ('vlr-payment-proofs', 'vlr-payment-proofs', false, 8388608, array['image/jpeg','image/png','image/webp']),
  ('vlr-return-photos', 'vlr-return-photos', false, 8388608, array['image/jpeg','image/png','image/webp'])
on conflict (id) do nothing;

create policy "vlr public product media read" on storage.objects for select to anon, authenticated using (bucket_id = 'vlr-product-media');
create policy "vlr admins manage product media" on storage.objects for all to authenticated using (bucket_id = 'vlr-product-media' and (select vlr_private.is_admin())) with check (bucket_id = 'vlr-product-media' and (select vlr_private.is_admin()));
create policy "vlr users upload payment proof" on storage.objects for insert to authenticated with check (bucket_id = 'vlr-payment-proofs' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "vlr users read own payment proof" on storage.objects for select to authenticated using (bucket_id = 'vlr-payment-proofs' and ((storage.foldername(name))[1] = (select auth.uid())::text or (select vlr_private.is_admin())));
create policy "vlr users upload return photos" on storage.objects for insert to authenticated with check (bucket_id = 'vlr-return-photos' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "vlr users read own return photos" on storage.objects for select to authenticated using (bucket_id = 'vlr-return-photos' and ((storage.foldername(name))[1] = (select auth.uid())::text or (select vlr_private.is_admin())));

insert into public.vlr_departments (slug, name, sort_order) values
  ('women', 'WOMEN', 1), ('men', 'MEN', 2), ('kids', 'KIDS', 3);

insert into public.vlr_categories (department_id, slug, name, sort_order)
select d.id, c.slug, c.name, c.sort_order
from public.vlr_departments d
join (values
  ('men','t-shirts','T-Shirts',1),('men','shirts','Shirts',2),('men','hoodies','Hoodies',3),('men','jackets','Jackets',4),('men','formal','Formal',5),('men','suits','Suits',6),('men','pants','Pants',7),('men','jeans','Jeans',8),('men','shoes','Shoes',9),('men','bags','Bags',10),('men','wallets','Wallets',11),('men','watches','Watches',12),('men','jewelry','Jewelry',13),('men','fragrance','Fragrance',14),
  ('women','dresses','Dresses',1),('women','tops','Tops',2),('women','shirts','Shirts',3),('women','jackets','Jackets',4),('women','pants','Pants',5),('women','jeans','Jeans',6),('women','skirts','Skirts',7),('women','shoes','Shoes',8),('women','heels','Heels',9),('women','handbags','Handbags',10),('women','purses','Purses',11),('women','jewelry','Jewelry',12),('women','watches','Watches',13),('women','fragrance','Fragrance',14),
  ('kids','girls','Girls',1),('kids','boys','Boys',2),('kids','baby','Baby',3),('kids','t-shirts','T-Shirts',4),('kids','dresses','Dresses',5),('kids','jackets','Jackets',6),('kids','pants','Pants',7),('kids','shoes','Shoes',8),('kids','bags','Bags',9),('kids','toys','Toys',10),('kids','educational-toys','Educational Toys',11),('kids','school','School',12)
) as c(department_slug,slug,name,sort_order) on c.department_slug = d.slug;

insert into public.vlr_collections (slug, name, description, cover_image_url, sort_order) values
  ('atelier-nocturne', 'Atelier Nocturne', 'Architectural evening pieces in oxblood and noir.', '/images/campaign/veloire-hero.webp', 1),
  ('the-quiet-form', 'The Quiet Form', 'Precise tailoring, enduring materials, restrained presence.', '/images/campaign/veloire-men.webp', 2),
  ('objets-prives', 'Objets Privés', 'Considered objects for the rituals of everyday life.', '/images/campaign/veloire-accessories.webp', 3);

with product_seed(slug,name,description,department_slug,category_slug,product_type,base_price,material,primary_image_url,is_featured,is_new_arrival) as (values
  ('sculpted-oxblood-gown','Sculpted Oxblood Gown','A column silhouette cut with a sculptural drape and restrained evening presence.','women','dresses','Clothing',1280000::numeric,'Silk crepe blend','/images/campaign/veloire-hero.webp',true,true),
  ('maison-noir-blazer','Maison Noir Blazer','Single-breasted tailoring with an elongated line and hand-finished interior.','men','jackets','Clothing',980000::numeric,'Wool and silk','/images/campaign/veloire-men.webp',true,true),
  ('rivoli-ivory-shirt','Rivoli Ivory Shirt','A fluid formal shirt balanced by a sharp point collar.','men','shirts','Clothing',420000::numeric,'Silk poplin','/images/campaign/veloire-men.webp',false,true),
  ('palais-leather-bag','Palais Leather Bag','Structured top-handle bag with a discreet sculptural clasp.','women','handbags','Leather Goods',760000::numeric,'Full-grain leather','/images/campaign/veloire-accessories.webp',true,true),
  ('minuit-timepiece','Minuit Timepiece','A slender evening watch with a minimal dial and polished case.','men','watches','Watch',1150000::numeric,'Steel and leather','/images/campaign/veloire-accessories.webp',true,false),
  ('ambre-voile-parfum','Ambre Voile Parfum','Dry amber, iris and cedar composed as a quiet, lingering veil.','women','fragrance','Fragrance',310000::numeric,'Eau de parfum 75ml','/images/campaign/veloire-accessories.webp',false,true),
  ('petite-nocturne-dress','Petite Nocturne Dress','A softly structured occasion dress designed for ease of movement.','kids','dresses','Kids Clothing',280000::numeric,'Cotton silk','/images/campaign/veloire-hero.webp',false,true),
  ('atelier-building-set','Atelier Building Set','A tactile architectural play set in responsibly sourced wood.','kids','educational-toys','Toy',145000::numeric,'FSC-certified wood','/images/campaign/veloire-accessories.webp',false,false)
)
insert into public.vlr_products (slug,name,description,department_id,category_id,product_type,base_price,material,care,shipping_note,return_policy,primary_image_url,hover_image_url,is_featured,is_new_arrival)
select p.slug,p.name,p.description,d.id,c.id,p.product_type,p.base_price,p.material,'Professional care recommended.','Complimentary signature packaging.','Returns accepted within 14 days of delivery.','/images/campaign/veloire-accessories.webp',p.primary_image_url,p.is_featured,p.is_new_arrival
from product_seed p
join public.vlr_departments d on d.slug = p.department_slug
join public.vlr_categories c on c.department_id = d.id and c.slug = p.category_slug;

insert into public.vlr_product_variants (product_id, sku, option_values, stock, price_adjustment)
select p.id, upper('VLR-' || substr(replace(p.id::text,'-',''),1,8) || '-01'),
  case
    when p.product_type = 'Clothing' then jsonb_build_object('Size','M','Color',case when p.slug like '%oxblood%' then 'Oxblood' else 'Noir' end)
    when p.product_type = 'Kids Clothing' then jsonb_build_object('Age','6–7 Years','Color','Oxblood')
    when p.product_type = 'Watch' then jsonb_build_object('Strap','Noir Leather','Dial','Ivory')
    when p.product_type = 'Leather Goods' then jsonb_build_object('Color','Oxblood','Material','Leather')
    when p.product_type = 'Toy' then jsonb_build_object('Age Range','5+ Years')
    else jsonb_build_object('Size','75 ml')
  end,
  case when p.product_type = 'Toy' then 12 else 8 end,
  0
from public.vlr_products p;

insert into public.vlr_ai_settings (id, enabled, system_note) values (true, true, 'Bilingual private stylist restricted to the live VÉLOIRE catalog.') on conflict (id) do nothing;
insert into public.vlr_store_settings (id) values (true) on conflict (id) do nothing;

insert into public.vlr_profiles (id, email, full_name, avatar_url, role)
select id, coalesce(email,''), coalesce(raw_user_meta_data ->> 'full_name', raw_user_meta_data ->> 'name'), raw_user_meta_data ->> 'avatar_url',
  case when lower(coalesce(email,'')) = 'lia.thedev@gmail.com' then 'admin' else 'customer' end
from auth.users
on conflict (id) do update set role = case when lower(excluded.email) = 'lia.thedev@gmail.com' then 'admin' else public.vlr_profiles.role end;

comment on table public.vlr_profiles is 'VÉLOIRE customer profiles; admin role is assigned only by trusted database logic.';
comment on table public.vlr_order_items is 'Immutable order-time product and variant snapshots for historical receipts.';
