create index vlr_addresses_user_idx on public.vlr_addresses(user_id);
create index vlr_admin_audit_actor_idx on public.vlr_admin_audit_logs(actor_id);
create index vlr_ai_settings_updated_by_idx on public.vlr_ai_settings(updated_by);
create index vlr_bag_variant_idx on public.vlr_bag_items(variant_id);
create index vlr_loyalty_user_idx on public.vlr_loyalty_transactions(user_id, created_at desc);
create index vlr_notifications_user_idx on public.vlr_notifications(user_id, created_at desc);
create index vlr_order_items_order_idx on public.vlr_order_items(order_id);
create index vlr_order_items_product_idx on public.vlr_order_items(product_id);
create index vlr_order_items_variant_idx on public.vlr_order_items(variant_id);
create index vlr_payments_user_idx on public.vlr_payments(user_id);
create index vlr_payments_verified_by_idx on public.vlr_payments(verified_by);
create index vlr_product_collections_collection_idx on public.vlr_product_collections(collection_id);
create index vlr_product_media_product_idx on public.vlr_product_media(product_id);
create index vlr_products_category_idx on public.vlr_products(category_id) where is_available;
create index vlr_recent_product_idx on public.vlr_recently_viewed(product_id);
create index vlr_return_items_order_item_idx on public.vlr_return_items(order_item_id);
create index vlr_returns_order_idx on public.vlr_returns(order_id);
create index vlr_returns_user_idx on public.vlr_returns(user_id, requested_at desc);
create index vlr_wishlist_product_idx on public.vlr_wishlist_items(product_id);
